#!/usr/bin/env ruby
# frozen_string_literal: true

require 'rubygems'
require 'bundler/setup'
require 'doomfire'
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = 'Usage: doomfire [options]'

  options[:sdl] = false
  opts.on('--sdl', 'Execute SDL version') do
    options[:sdl] = true
  end

  opts.on('-h', '--help', 'Display this screen') do
    puts opts
    exit
  end
end.parse!

if options[:sdl]
  begin
    require 'doomfire/ffi_sdl'
    require 'doomfire/sdl'
    Doomfire::SDL.new.run
  rescue Fiddle::DLError
    puts 'You need to install libSDL2 to use the SDL output.'
  end
else
  Doomfire::Terminal.new.run
end
